---
- name: Complete MongoDB wipe
  hosts: all
  become: yes
  tasks:

    - name: Remove MongoDB packages
      yum:
        name:
          - mongodb-org
          - mongodb-org-server
          - mongodb-org-mongos
          - mongodb-org-tools
          - mongodb-mongosh
        state: absent

    - name: Remove all MongoDB data and config
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /mnt/data/mongodb
        - /mnt/data/mongodb-config
        - /mnt/data/mongodb-arbiter
        - /mnt/data/meta
        - /etc/mongodb-cls
        - /var/log/mongodb
        - /var/lib/mongo

    - name: Clean MongoDB PID and lock files
      shell: rm -rf /var/run/mongodb/* /tmp/mongodb-*.sock
      ignore_errors: yes

    - name: Remove mongod user and group
      user:
        name: mongod
        state: absent
        remove: yes
      ignore_errors: yes

    - name: Show wipe complete
      debug:
        msg: "Complete MongoDB wipe done on {{ inventory_hostname }}"

