---
- name: Initialize config server replica set
  hosts: 192.168.121.106
  become: yes
  vars_files:
    - roles/mongodb_cluster/defaults/main.yml
  tasks:
    - name: Check if config server is already initialized
      shell: |
        mongosh --port {{ config_port }} --quiet --eval 'rs.status()'
      register: config_rs_status
      failed_when: config_rs_status.rc != 0 and "isMaster" not in config_rs_status.stdout
      changed_when: False

    - name: Initialize config replica set
      shell: |
        mongosh --port {{ config_port }} --quiet --eval '
        rs.initiate({
          _id: "{{ config_replset }}",
          configsvr: true,
          members: [
            { _id: 0, host: "192.168.121.106:{{ config_port }}" },
            { _id: 1, host: "192.168.121.107:{{ config_port }}" },
            { _id: 2, host: "192.168.121.108:{{ config_port }}" }
          ]
        })
        '
      register: config_rs_init
      when: config_rs_status.rc != 0 and "isMaster" not in config_rs_status.stdout

    - name: Show result
      debug:
        var: config_rs_init.stdout
      when: config_rs_status.rc != 0 and "isMaster" not in config_rs_status.stdout

    - name: Wait for replica set
      pause:
        seconds: 30
      when: config_rs_status.rc != 0 and "isMaster" not in config_rs_status.stdout

- name: Initialize data replica set
  hosts: 192.168.121.101
  become: yes
  vars_files:
    - roles/mongodb_cluster/defaults/main.yml
  tasks:
    - name: Check if data replica set is already initialized
      shell: |
        mongosh --port {{ data_port }} --quiet --eval 'rs.status()'
      register: data_rs_status
      failed_when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout
      changed_when: False

    - name: Initialize data replica set
      shell: |
        mongosh --port {{ data_port }} --quiet --eval '
        rs.initiate({
          _id: "{{ data_replset }}",
          members: [
            { _id: 0, host: "192.168.121.101:{{ data_port }}" },
            { _id: 1, host: "192.168.121.102:{{ data_port }}" },
            { _id: 2, host: "192.168.121.103:{{ data_port }}" },
            { _id: 3, host: "192.168.121.104:{{ data_port }}" },
            { _id: 4, host: "192.168.121.105:{{ data_port }}" },
            { _id: 5, host: "192.168.121.108:{{ arbiter_port }}", arbiterOnly: true }
          ]
        })
        '
      register: data_rs_init
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Show result
      debug:
        var: data_rs_init.stdout
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Wait for replica set
      pause:
        seconds: 30
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Add shard to cluster
      shell: |
        mongosh --port {{ mongos_port }} --quiet --eval '
        sh.addShard("{{ data_replset }}/192.168.121.101:{{ data_port }},192.168.121.102:{{ data_port }},192.168.121.103:{{ data_port }},192.168.121.104:{{ data_port }},192.168.121.105:{{ data_port }}")
        '
      register: shard_add
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Show shard add result
      debug:
        var: shard_add.stdout
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Check cluster status
      shell: |
        mongosh --port {{ mongos_port }} --quiet --eval 'sh.status()'
      register: cluster_status
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

    - name: Show cluster status
      debug:
        var: cluster_status.stdout
      when: data_rs_status.rc != 0 and "isMaster" not in data_rs_status.stdout

