- name: Initialize data replica set
  hosts: 192.168.121.101
  become: yes
  vars_files:
    - roles/mongodb_cluster/defaults/main.yml
  tasks:
    - name: Initialize data replica set
      shell: |
        mongosh --port {{ data_port }} --quiet --eval '
        rs.initiate({
          _id: "{{ data_replset }}",
          members: [
            { _id: 0, host: "192.168.121.101:{{ data_port }}" },
            { _id: 1, host: "192.168.121.102:{{ data_port }}" },
            { _id: 2, host: "192.168.121.103:{{ data_port }}" },
            { _id: 3, host: "192.168.121.104:{{ data_port }}" },
            { _id: 4, host: "192.168.121.105:{{ data_port }}" },
            { _id: 5, host: "192.168.121.108:{{ arbiter_port }}", arbiterOnly: true }
          ]
        })
        '
      register: data_rs_init
      
    - name: Show result
      debug:
        var: data_rs_init.stdout

    - name: Wait for replica set
      pause:
        seconds: 30

    - name: Force election - set priority for node 101
      shell: |
        mongosh --port {{ data_port }} --quiet --eval '
        cfg = rs.conf();
        cfg.members[0].priority = 2;
        cfg.members[1].priority = 1;
        cfg.members[2].priority = 1;
        cfg.members[3].priority = 1;
        cfg.members[4].priority = 1;
        rs.reconfig(cfg);
        '
      register: election_result
      
    - name: Wait for election
      pause:
        seconds: 15


    - name: Add shard to cluster
      shell: |
        mongosh --port {{ mongos_port }} --quiet --eval '
        sh.addShard("{{ data_replset }}/192.168.121.101:{{ data_port }},192.168.121.102:{{ data_port }},192.168.121.103:{{ data_port }},192.168.121.104:{{ data_port }},192.168.121.105:{{ data_port }}")
        '
      register: shard_add
      
    - name: Show shard add result
      debug:
        var: shard_add.stdout

    - name: Check cluster status
      shell: |
        mongosh --port {{ mongos_port }} --quiet --eval 'sh.status()'
      register: cluster_status
      
    - name: Show cluster status
      debug:
        var: cluster_status.stdout
