---
- name: Prepare systems for MongoDB cluster
  hosts: all
  become: yes
  tasks:
    - name: Disable SELinux permanently
      lineinfile:
        path: /etc/selinux/config
        regexp: '^SELINUX='
        line: 'SELINUX=disabled'
      register: selinux_config
    - name: Disable SELinux immediately
      command: setenforce 0
      ignore_errors: yes
    - name: Stop and disable firewalld
      systemd:
        name: firewalld
        state: stopped
        enabled: no
      ignore_errors: yes
    - name: Stop and disable mongod
      systemd:
        name: mongod
        state: stopped
        enabled: no
      ignore_errors: yes
    - name: Install chrony for NTP
      yum:
        name: chrony
        state: present
    - name: Ensure chronyd is started and enabled
      systemd:
        name: chronyd
        state: started
        enabled: yes
    - name: Force time sync
      command: chronyc makestep
      ignore_errors: yes
    - name: Check time sync status
      command: chronyc tracking
      register: chrony_status
      changed_when: false
    - name: Check if /var/run/mongodb exists
      stat:
        path: /var/run/mongodb
      register: mongodb_dir_stat
    - name: Create /var/run/mongodb if it does not exist
      file:
        path: /var/run/mongodb
        state: directory
        mode: '0755'
        owner: mongod
        group: mongod
      when: mongodb_dir_stat.stat.exists == false
    - name: Ensure /var/run/mongodb is owned by mongod:mongod
      file:
        path: /var/run/mongodb
        owner: mongod
        group: mongod
        mode: '0755'
    - name: Stop mongodb-cluster
      command: systemctl stop mongo*
    - name: Display time sync status
      debug:
        var: chrony_status.stdout_lines

